// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmbBtya-Hmxx_jA9wZlphBQXnsbXUInXw',
    appId: '1:111451882647:web:f5662992345a71ae7e95d2',
    messagingSenderId: '111451882647',
    projectId: 'chat-app-a8afe',
    authDomain: 'chat-app-a8afe.firebaseapp.com',
    storageBucket: 'chat-app-a8afe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEDITIKW3Tisy5TPiIXyGcfGrmdY6qbgo',
    appId: '1:111451882647:android:be8c9fb2e2a3f2f17e95d2',
    messagingSenderId: '111451882647',
    projectId: 'chat-app-a8afe',
    storageBucket: 'chat-app-a8afe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8G-AS2caqPMRNZw3OonglqlilPX9y3aQ',
    appId: '1:111451882647:ios:6cc8713b87876f1f7e95d2',
    messagingSenderId: '111451882647',
    projectId: 'chat-app-a8afe',
    storageBucket: 'chat-app-a8afe.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8G-AS2caqPMRNZw3OonglqlilPX9y3aQ',
    appId: '1:111451882647:ios:718f0838408cc6c57e95d2',
    messagingSenderId: '111451882647',
    projectId: 'chat-app-a8afe',
    storageBucket: 'chat-app-a8afe.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
